name: deploy-qa
on:
  push:
    branches:
      - dev
env:
  PROD_HOST: qa.mural.practice.uffs.cc
  PROD_WEB_DIRECTORY: /home/practiceqamural/qa.mural.practice.uffs.cc
  COMPOSER_BIN: php-7.3 ~/.php/composer/composer
  PHP_BIN: php-7.3
jobs:
  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.PROD_HOST }}
        username: ${{ secrets.QA_USERNAME }}
        password: ${{ secrets.QA_PASSWORD }}
        script: |
          cd ${{ env.PROD_WEB_DIRECTORY }}
          git reset --hard
          git pull
          ${{ env.COMPOSER_BIN }} install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          ${{ env.PHP_BIN }} artisan migrate
          npm install
          npm run production
